"""Heuristic quality filters for raw code documents.

Adapted from the RefineCode / OpenCoder cleaning recipe (OpenCoder paper, Sec. 2.1
"Data Processing", the code-file heuristic rules) and its StarCoder ancestry. These
are deliberately language-agnostic, cheap, single-pass rules meant to drop the
obviously-bad files (auto-generated blobs, data dumps, minified one-liners,
near-empty stubs) before the expensive dedup + tokenization stages.

Each rule returns a rejection reason string, or None to keep. `filter_document`
runs them in order and returns the first reason (or None). Thresholds are exposed
on `CodeFilter` so they can be tuned per corpus; the defaults are conservative.
"""

from __future__ import annotations

from dataclasses import dataclass

# Markers that strongly indicate machine-generated files (OpenCoder drops these;
# they hurt more than help a from-scratch code model).
_AUTOGEN_MARKERS = (
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "do not modify",
    "generated by",
    "this file was generated",
    "@generated",
    "code generated by",
)


@dataclass
class CodeFilter:
    min_chars: int = 32  # near-empty stubs
    max_chars: int = 1_000_000  # ~1 MB; huge files are usually data, not code
    min_lines: int = 3
    max_avg_line_length: float = 100.0  # data dumps / minified code
    max_line_length: int = 1000  # single mega-line (minified / base64 blobs)
    min_alpha_fraction: float = 0.25  # code is mostly letters+symbols, not raw bytes
    max_non_ascii_fraction: float = 0.40  # binary-ish / heavily non-latin blobs
    max_digit_fraction: float = 0.50  # numeric tables / serialized weights
    drop_autogenerated: bool = True

    def reject_reason(self, text: str) -> str | None:
        n = len(text)
        if n < self.min_chars:
            return "too_short"
        if n > self.max_chars:
            return "too_long"

        lines = text.split("\n")
        if len(lines) < self.min_lines:
            return "too_few_lines"

        max_len = max((len(ln) for ln in lines), default=0)
        if max_len > self.max_line_length:
            return "max_line_length"
        if (n / max(len(lines), 1)) > self.max_avg_line_length:
            return "avg_line_length"

        alpha = sum(c.isalpha() for c in text)
        if alpha / n < self.min_alpha_fraction:
            return "low_alpha_fraction"

        digits = sum(c.isdigit() for c in text)
        if digits / n > self.max_digit_fraction:
            return "high_digit_fraction"

        non_ascii = sum(ord(c) > 127 for c in text)
        if non_ascii / n > self.max_non_ascii_fraction:
            return "high_non_ascii"

        if self.drop_autogenerated:
            head = text[:2048].lower()
            if any(m in head for m in _AUTOGEN_MARKERS):
                return "autogenerated"

        return None

    def keep(self, text: str) -> bool:
        return self.reject_reason(text) is None
